name: textify
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_custom_clippers: ^2.0.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  http:
  web3dart: ^2.3.5

flutter:

  uses-material-design: true
  assets:
    - assets/
